language: node_js
sudo: false
notifications:
  email: false
node_js:
  - "8" # stable
  - "6" # LTS
  # Issue in underlying `fitbit-node` module
  # - "4" # maintenance
cache:
  directories:
    - node_modules
